import {
  CitizenReportItem,
  ReviewerStats,
  TimelineEvent,
  ReviewNote,
} from "./types";

export const MOCK_REVIEWER_STATS: ReviewerStats = {
  pendingReviews: 24,
  reviewedByMe: 38,
  assignedToMe: 12,
  averageReviewTimeMinutes: 18,
  needMoreInformation: 6,
  forwardedToInspection: 14,
  verifiedReports: 38,
  rejectedReports: 7,
};

export const MOCK_INSPECTORS = [
  { id: "INS-104", name: "Inspector Ramesh Sharma", jurisdiction: "Ludhiana Central & Gill Road", activeCases: 4 },
  { id: "INS-108", name: "Inspector Sunita Kulkarni", jurisdiction: "Mumbai South & Dadar Zone", activeCases: 7 },
  { id: "INS-112", name: "Inspector Rajesh Gupta", jurisdiction: "New Delhi Central District", activeCases: 5 },
  { id: "INS-115", name: "Inspector Anand Rao", jurisdiction: "Bengaluru South & Koramangala", activeCases: 3 },
  { id: "INS-119", name: "Inspector Meenakshi Rathore", jurisdiction: "Jaipur Urban Zone 1", activeCases: 6 },
  { id: "INS-124", name: "Inspector Hitesh Patel", jurisdiction: "Ahmedabad Railway & Metro Hub", activeCases: 8 },
];

export const MOCK_REPORTS: CitizenReportItem[] = [
  {
    id: "rep-001",
    reportNumber: "CR-2026-0001",
    userId: "usr-cit-1092",
    citizenNameMasked: "Gurpreet S. (Citizen #1092)",
    citizenPhoneMasked: "+91 98765-XXXXX",
    scanId: "scn-84920",
    issueType: "INCORRECT_WEIGHT",
    issueLabel: "Incorrect Weight / Net Quantity Shortfall",
    description:
      "Purchased sealed 1-Litre bottle of Kachi Ghani Mustard Oil. Measured net volume at 870 ml using calibrated beaker. Package claims Net Volume 1000 ml. Maximum Permissible Error (MPE) under Fifth Schedule of PCR 2011 is 15 ml; observed deficiency is 130 ml (~13%).",
    status: "PENDING_REVIEW",
    priority: "HIGH",
    shopName: "Verma Provision Store",
    shopkeeperName: "Sunil Verma",
    shopAddress: "Shop No. 14, Gill Road Market, Near Grain Market",
    shopCity: "Ludhiana",
    shopState: "Punjab",
    shopPinCode: "141003",
    latitude: 30.8986,
    longitude: 75.8573,
    locationAccuracy: 6.2,
    productSnapshot: {
      productName: "Kachi Ghani Pure Mustard Oil (1L)",
      brand: "Swad Gold Agro",
      genericName: "Edible Mustard Oil",
      category: "Edible Oils & Foods",
      manufacturerName: "Swad Agro Processors Pvt Ltd",
      manufacturerAddress: "Industrial Area Phase II, Jalandhar, Punjab - 144001",
      packerName: "Swad Agro Processors Pvt Ltd",
      packerAddress: "Industrial Area Phase II, Jalandhar, Punjab - 144001",
      countryOfOrigin: "India",
      declaredNetQuantity: "1 L (910 g)",
      declaredMRP: "₹ 185.00 (Incl. of all taxes)",
      unitSalePrice: "₹ 0.185 / ml",
      monthYearOfManufacture: "01/2026",
      expiryBestBefore: "9 Months from packaging",
      batchOrLotNumber: "SGMO-2026-08A",
      barcodeGTIN: "8901234567890",
      consumerCareEmail: "customercare@swadagro.in",
      consumerCarePhone: "1800-200-8899",
    },
    analysisSnapshot: {
      ocrRawText:
        "SWAD GOLD KACHI GHANI MUSTARD OIL NET VOL 1 LITRE (910g) MRP RS 185.00 INCL OF ALL TAXES PKG 01/2026 BATCH SGMO-2026-08A MFR SWAD AGRO JALANDHAR PUNJAB CONSUMER CARE 1800-200-8899",
      ocrConfidence: 94.8,
      detectedBarcodes: ["8901234567890"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 92.4,
      ruleChecks: [
        {
          ruleNumber: "Rule 6(1)(a)",
          ruleTitle: "Product Identity & Generic Name",
          requirement: "Name & description of commodity clearly indicated",
          declaredValue: "Edible Mustard Oil",
          observedValue: "Edible Mustard Oil",
          status: "COMPLIANT",
          confidenceScore: 98,
        },
        {
          ruleNumber: "Rule 6(1)(b)",
          ruleTitle: "Net Quantity Declaration",
          requirement: "Standard units of weight/measure and verified volume",
          declaredValue: "1000 ml",
          observedValue: "870 ml (Evidence photo: Calibrated Beaker)",
          status: "NON_COMPLIANT",
          confidenceScore: 95,
          notes: "Deficiency of 130 ml exceeds Maximum Permissible Error (15 ml) by 866%.",
        },
        {
          ruleNumber: "Rule 6(1)(c)",
          ruleTitle: "Maximum Retail Price (MRP)",
          requirement: "Clear MRP inclusive of all taxes and unit sale price",
          declaredValue: "₹ 185.00 (USP ₹0.185/ml)",
          observedValue: "₹ 185.00 declared clearly",
          status: "COMPLIANT",
          confidenceScore: 96,
        },
        {
          ruleNumber: "Rule 6(1)(d)",
          ruleTitle: "Month & Year of Manufacture",
          requirement: "Legible packaging date and expiry statement",
          declaredValue: "01/2026",
          observedValue: "01/2026 (Inkjet printed on neck)",
          status: "COMPLIANT",
          confidenceScore: 94,
        },
        {
          ruleNumber: "Rule 6(1)(e)",
          ruleTitle: "Consumer Care Details",
          requirement: "Valid helpline telephone, email, and designated officer",
          declaredValue: "1800-200-8899 / customercare@swadagro.in",
          observedValue: "1800-200-8899 / customercare@swadagro.in",
          status: "COMPLIANT",
          confidenceScore: 97,
        },
      ],
      highlightedIssues: [
        "Net quantity measured by citizen is significantly below declared 1L package volume.",
        "Requires verification of scale calibration or forwarding to district inspector for physical sample seizure.",
      ],
    },
    evidence: [
      {
        id: "ev-101",
        storageKey: "reports/CR-2026-0001/front_label.jpg",
        originalFileName: "mustard_oil_front.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2458900,
        imageType: "FRONT_LABEL",
        url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-10T14:32:00Z",
        resolution: "3024 x 4032",
      },
      {
        id: "ev-102",
        storageKey: "reports/CR-2026-0001/beaker_measurement.jpg",
        originalFileName: "liquid_volume_scale.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 3120000,
        imageType: "WEIGHT_SCALE",
        url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-10T14:36:12Z",
        resolution: "3024 x 4032",
      },
      {
        id: "ev-103",
        storageKey: "reports/CR-2026-0001/purchase_bill.jpg",
        originalFileName: "retail_invoice_gill_road.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 1845000,
        imageType: "INVOICE",
        url: "https://images.unsplash.com/photo-1554415707-9e44667ff258?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-10T14:40:05Z",
        resolution: "2448 x 3264",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-01",
        authorName: "Officer Sharma",
        authorRole: "Senior Reviewer",
        content:
          "Visual inspection of bottle neck shows fill line visibly below shoulder level. Beaker evidence appears clear with meniscus at 870ml mark. Pre-inspection notice recommended under PCR Rule 27.",
        createdAt: "2026-09-11T10:15:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-01",
        timestamp: "2026-09-10T14:42:00Z",
        action: "Citizen Submitted Report",
        actor: "Citizen #1092",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
        details: "Report filed with 3 photographic evidence attachments and retail invoice.",
      },
      {
        id: "tl-02",
        timestamp: "2026-09-11T09:30:00Z",
        action: "Assigned to Reviewer",
        actor: "System Dispatcher",
        actorRole: "Automated Rule",
        previousStatus: "PENDING_REVIEW",
        newStatus: "PENDING_REVIEW",
        details: "Assigned based on North Zone Jurisdiction (Punjab/Ludhiana).",
      },
    ],
    createdAt: "2026-09-10T14:42:00Z",
    updatedAt: "2026-09-11T10:15:00Z",
  },
  {
    id: "rep-002",
    reportNumber: "CR-2026-0002",
    userId: "usr-cit-2401",
    citizenNameMasked: "Pooja M. (Citizen #2401)",
    citizenPhoneMasked: "+91 98201-XXXXX",
    scanId: "scn-84928",
    issueType: "DUAL_MRP",
    issueLabel: "Dual MRP / Overwritten Sticker on Price",
    description:
      "5kg bag of Basmati Rice has factory printed MRP of ₹340.00 obliterated with permanent marker, and a printed retailer adhesive barcode sticker of ₹425.00 placed on top. Cashier charged ₹425 on invoice.",
    status: "UNDER_REVIEW",
    priority: "HIGH",
    shopName: "Laxmi Super Bazaar",
    shopkeeperName: "Dinesh K. Shah",
    shopAddress: "Plot 88, NC Kelkar Road, Dadar West",
    shopCity: "Mumbai",
    shopState: "Maharashtra",
    shopPinCode: "400028",
    latitude: 19.0222,
    longitude: 72.8427,
    locationAccuracy: 4.8,
    productSnapshot: {
      productName: "Select Royal Traditional Basmati Rice (5kg)",
      brand: "Kohinoor Heritage",
      genericName: "Aged Basmati Rice",
      category: "Grains & Cereals",
      manufacturerName: "Kohinoor Foods & Grains Ltd",
      manufacturerAddress: "G.T. Karnal Road, Murthal, Sonipat, Haryana - 131027",
      countryOfOrigin: "India",
      declaredNetQuantity: "5.0 kg",
      declaredMRP: "₹ 340.00 (Mfr Printed) / ₹ 425.00 (Sticker)",
      unitSalePrice: "₹ 68.00 / kg (Original)",
      monthYearOfManufacture: "12/2025",
      expiryBestBefore: "24 Months from packaging",
      batchOrLotNumber: "KH-BR-5K-991",
      barcodeGTIN: "8902456711223",
      consumerCareEmail: "feedback@kohinoorgrains.com",
      consumerCarePhone: "011-45678900",
    },
    analysisSnapshot: {
      ocrRawText:
        "KOHINOOR SELECT AGED BASMATI RICE 5KG NET WT 5.0kg MRP RS 340.00 INCL TAXES [STICKER DETECTED: MRP RS 425.00 LAXMI SUPER BAZAAR]",
      ocrConfidence: 96.2,
      detectedBarcodes: ["8902456711223"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 95.0,
      ruleChecks: [
        {
          ruleNumber: "Rule 18(2)",
          ruleTitle: "No Alteration of Stated Price",
          requirement: "No retail dealer shall alter, obliterate or smudge the MRP declared by the manufacturer",
          declaredValue: "₹ 340.00",
          observedValue: "Overwritten sticker of ₹ 425.00 pasted directly above",
          status: "NON_COMPLIANT",
          confidenceScore: 98,
          notes: "Clear violation of Rule 18(2) of Packaged Commodities Rules 2011.",
        },
        {
          ruleNumber: "Rule 6(1)(c)",
          ruleTitle: "Single Definite MRP Declaration",
          requirement: "Single unambiguous MRP inclusive of all taxes",
          declaredValue: "Dual MRP present",
          observedValue: "Two conflicting price stamps visible simultaneously",
          status: "NON_COMPLIANT",
          confidenceScore: 97,
        },
      ],
      highlightedIssues: [
        "Unauthorized price sticker pasted over manufacturer printed MRP.",
        "Retail tax invoice matches the altered higher price (₹425 vs ₹340).",
      ],
    },
    evidence: [
      {
        id: "ev-201",
        storageKey: "reports/CR-2026-0002/mrp_sticker_closeup.jpg",
        originalFileName: "mrp_sticker_peeled.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2890000,
        imageType: "MRP_STAMP",
        url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-11T11:20:00Z",
        resolution: "3024 x 4032",
      },
      {
        id: "ev-202",
        storageKey: "reports/CR-2026-0002/invoice_slip.jpg",
        originalFileName: "laxmi_super_bazaar_receipt.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 1980000,
        imageType: "INVOICE",
        url: "https://images.unsplash.com/photo-1554415707-9e44667ff258?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-11T11:25:30Z",
        resolution: "2448 x 3264",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-02",
        authorName: "Officer Sharma",
        authorRole: "Reviewer",
        content:
          "Direct violation under Section 36(1) of Legal Metrology Act, 2009 read with Rule 18(2) of PCR 2011. Evidence clearly captures underlying original print ₹340 and retailer barcode sticker at ₹425.",
        createdAt: "2026-09-11T12:00:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-201",
        timestamp: "2026-09-11T11:30:00Z",
        action: "Report Submitted",
        actor: "Citizen #2401",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
      {
        id: "tl-202",
        timestamp: "2026-09-11T11:45:00Z",
        action: "Review Started",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "PENDING_REVIEW",
        newStatus: "UNDER_REVIEW",
      },
    ],
    createdAt: "2026-09-11T11:30:00Z",
    updatedAt: "2026-09-11T12:00:00Z",
  },
  {
    id: "rep-003",
    reportNumber: "CR-2026-0003",
    userId: "usr-cit-4819",
    citizenNameMasked: "Arjun N. (Citizen #4819)",
    citizenPhoneMasked: "+91 99112-XXXXX",
    scanId: "scn-84941",
    issueType: "COUNTRY_OF_ORIGIN_MISSING",
    issueLabel: "Missing Country of Origin on Imported Food",
    description:
      "Packaged premium dark chocolate hazelnut spread imported from abroad sold in upscale store without Country of Origin declaration, without Indian Importer name/address, and with zero customer care phone number.",
    status: "PENDING_REVIEW",
    priority: "MEDIUM",
    shopName: "Delhi Gourmet Haven",
    shopkeeperName: "Vipin Mehra",
    shopAddress: "B-22, Inner Circle, Connaught Place",
    shopCity: "New Delhi",
    shopState: "Delhi",
    shopPinCode: "110001",
    latitude: 28.6328,
    longitude: 77.2197,
    locationAccuracy: 5.1,
    productSnapshot: {
      productName: "Artisanal Dark Chocolate Hazelnut Spread (350g)",
      brand: "Alpine Delights",
      genericName: "Cocoa Hazelnut Spread",
      category: "Imported Foods & Confectionery",
      countryOfOrigin: "NOT DECLARED",
      declaredNetQuantity: "350 g",
      declaredMRP: "₹ 690.00",
      barcodeGTIN: "7613035981123",
      importerName: "NOT DECLARED",
      importerAddress: "NOT DECLARED",
      consumerCareEmail: "NOT DECLARED",
    },
    analysisSnapshot: {
      ocrRawText:
        "ALPINE DELIGHTS DARK CHOCOLATE HAZELNUT SPREAD NET WT 350G INGREDIENTS: SUGAR PALM OIL HAZELNUTS COCOA MRP RS 690.00",
      ocrConfidence: 91.5,
      detectedBarcodes: ["7613035981123"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 89.2,
      ruleChecks: [
        {
          ruleNumber: "Rule 6(1)(aa)",
          ruleTitle: "Name of Country of Origin or Manufacture",
          requirement: "Mandatory declaration of country of origin on all imported pre-packaged commodities",
          declaredValue: "Missing",
          observedValue: "No declaration on label",
          status: "NON_COMPLIANT",
          confidenceScore: 98,
        },
        {
          ruleNumber: "Rule 6(1)(a)",
          ruleTitle: "Importer Details Declaration",
          requirement: "Name and complete address of the importer on imported goods",
          declaredValue: "Missing",
          observedValue: "No Indian importer address found on packaging",
          status: "NON_COMPLIANT",
          confidenceScore: 94,
        },
      ],
      highlightedIssues: [
        "Violation of Rule 6(1)(aa) requiring explicit Country of Origin.",
        "Missing domestic importer credentials as mandated by Legal Metrology (Packaged Commodities) Amendment Rules.",
      ],
    },
    evidence: [
      {
        id: "ev-301",
        storageKey: "reports/CR-2026-0003/back_label_wrap.jpg",
        originalFileName: "chocolate_spread_wrap.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2650000,
        imageType: "BACK_LABEL",
        url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-10T16:00:00Z",
        resolution: "3024 x 4032",
      },
    ],
    assignedReviewerId: "rev-8411",
    assignedReviewerName: "Officer K. Rao",
    reviewNotes: [],
    timeline: [
      {
        id: "tl-301",
        timestamp: "2026-09-10T16:15:00Z",
        action: "Citizen Submitted Report",
        actor: "Citizen #4819",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
    ],
    createdAt: "2026-09-10T16:15:00Z",
    updatedAt: "2026-09-10T16:15:00Z",
  },
  {
    id: "rep-004",
    reportNumber: "CR-2026-0004",
    userId: "usr-cit-5521",
    citizenNameMasked: "Naveen K. (Citizen #5521)",
    citizenPhoneMasked: "+91 94480-XXXXX",
    scanId: "scn-84955",
    issueType: "NON_STANDARD_UNIT",
    issueLabel: "Non-Standard Pack Size & Missing Helpline",
    description:
      "Detergent powder packaged in an arbitrary 825g net quantity packet to mislead buyers comparing price with standard 1kg pouches. Also, consumer grievance helpline telephone is omitted.",
    status: "NEED_MORE_INFORMATION",
    priority: "MEDIUM",
    shopName: "Sri Krishna Traders",
    shopkeeperName: "R. Muralidharan",
    shopAddress: "80 Feet Road, 4th Block, Koramangala",
    shopCity: "Bengaluru",
    shopState: "Karnataka",
    shopPinCode: "560034",
    latitude: 12.9345,
    longitude: 77.6265,
    locationAccuracy: 4.2,
    productSnapshot: {
      productName: "BrightWave Concentrated Detergent Powder",
      brand: "BrightWave Clean",
      genericName: "Synthetic Laundry Detergent",
      category: "Household & Cleaning Goods",
      manufacturerName: "Wave Hygiene Chemicals Pvt Ltd",
      manufacturerAddress: "Peenya Industrial Area Phase 1, Bengaluru - 560058",
      countryOfOrigin: "India",
      declaredNetQuantity: "825 g",
      declaredMRP: "₹ 110.00",
      unitSalePrice: "₹ 0.133 / g",
      monthYearOfManufacture: "02/2026",
      batchOrLotNumber: "BW-26-825",
      barcodeGTIN: "8908812345009",
      consumerCareEmail: "care@brightwaveclean.in",
      consumerCarePhone: "NOT PRINTED",
    },
    analysisSnapshot: {
      ocrRawText:
        "BRIGHTWAVE DETERGENT NET WT 825g MRP RS 110.00 USP 0.133/g PEENYA IND AREA BENGALURU CARE EMAIL: CARE@BRIGHTWAVECLEAN.IN",
      ocrConfidence: 93.0,
      detectedBarcodes: ["8908812345009"],
      preliminaryResult: "SUSPECTED_NON_COMPLIANCE",
      overallConfidence: 88.0,
      ruleChecks: [
        {
          ruleNumber: "Rule 5 / Second Schedule",
          ruleTitle: "Standard Quantities of Specified Commodities",
          requirement: "Detergent powders must be packed in prescribed quantities (e.g. 500g, 1kg, 2kg)",
          declaredValue: "825 g",
          observedValue: "825 g",
          status: "FLAGGED_FOR_REVIEW",
          confidenceScore: 82,
          notes: "Need verification if this package category qualifies under exemption under recent 2022 notification.",
        },
        {
          ruleNumber: "Rule 6(1)(e)",
          ruleTitle: "Consumer Care Telephone Number",
          requirement: "Mandatory telephone number in addition to email",
          declaredValue: "Email only",
          observedValue: "Telephone missing from pack label",
          status: "NON_COMPLIANT",
          confidenceScore: 96,
        },
      ],
      highlightedIssues: [
        "Pack quantity 825g deviates from standard 1000g packaging.",
        "Missing contact telephone number for consumer complaints.",
      ],
    },
    evidence: [
      {
        id: "ev-401",
        storageKey: "reports/CR-2026-0004/detergent_front.jpg",
        originalFileName: "brightwave_pouch.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2120000,
        imageType: "FRONT_LABEL",
        url: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-09T18:00:00Z",
        resolution: "3024 x 4032",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-401",
        authorName: "Officer Sharma",
        authorRole: "Reviewer",
        content:
          "Requested citizen to provide photo of the back gusset and seal to confirm if second phone number is stamped during sealing.",
        createdAt: "2026-09-11T08:30:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-401",
        timestamp: "2026-09-09T18:15:00Z",
        action: "Report Submitted",
        actor: "Citizen #5521",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
      {
        id: "tl-402",
        timestamp: "2026-09-10T11:00:00Z",
        action: "More Information Requested",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "PENDING_REVIEW",
        newStatus: "NEED_MORE_INFORMATION",
        details: "Requested clearer image of back panel seal area.",
      },
    ],
    createdAt: "2026-09-09T18:15:00Z",
    updatedAt: "2026-09-10T11:00:00Z",
  },
  {
    id: "rep-005",
    reportNumber: "CR-2026-0005",
    userId: "usr-cit-6780",
    citizenNameMasked: "Ananya S. (Citizen #6780)",
    citizenPhoneMasked: "+91 94140-XXXXX",
    scanId: "scn-84968",
    issueType: "DATE_DECLARATION_MISSING",
    issueLabel: "Missing Date of Manufacture & Expiry",
    description:
      "High-end skincare facial serum sold in mono-carton box completely devoid of Month/Year of Manufacture and Best Before date on outer packaging.",
    status: "VERIFIED",
    priority: "HIGH",
    shopName: "Pink City Wellness Store",
    shopkeeperName: "Mohit Choudhary",
    shopAddress: "Plot 12, Near Raj Mandir Cinema, MI Road",
    shopCity: "Jaipur",
    shopState: "Rajasthan",
    shopPinCode: "302001",
    latitude: 26.9196,
    longitude: 75.8086,
    locationAccuracy: 5.8,
    productSnapshot: {
      productName: "Glow Radiance 10% Vitamin C Serum (30ml)",
      brand: "DermaElite Naturals",
      genericName: "Cosmetic Face Serum",
      category: "Cosmetics & Personal Care",
      manufacturerName: "DermaElite Formulations Pvt Ltd",
      manufacturerAddress: "Sitapura Industrial Area, Jaipur - 302022",
      countryOfOrigin: "India",
      declaredNetQuantity: "30 ml",
      declaredMRP: "₹ 799.00 (Incl. of all taxes)",
      unitSalePrice: "₹ 26.63 / ml",
      monthYearOfManufacture: "NOT PRINTED ON OUTER CARTON",
      expiryBestBefore: "NOT PRINTED ON OUTER CARTON",
      batchOrLotNumber: "DEN-VC-2601",
      barcodeGTIN: "8906001239876",
      consumerCareEmail: "support@dermaelite.in",
      consumerCarePhone: "0141-2889900",
    },
    analysisSnapshot: {
      ocrRawText:
        "DERMAELITE NATURALS GLOW RADIANCE VITAMIN C 30ML MRP 799.00 INCL TAXES SITAPURA JAIPUR BATCH DEN-VC-2601 [MFG DATE: MISSING]",
      ocrConfidence: 97.4,
      detectedBarcodes: ["8906001239876"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 96.1,
      ruleChecks: [
        {
          ruleNumber: "Rule 6(1)(d)",
          ruleTitle: "Month & Year of Manufacture/Pre-packing",
          requirement: "Clear declaration of month and year of pre-packaging on primary and secondary package",
          declaredValue: "Missing on carton",
          observedValue: "Blank date stamp area on bottom carton flap",
          status: "NON_COMPLIANT",
          confidenceScore: 98,
        },
      ],
      highlightedIssues: [
        "Direct violation of Rule 6(1)(d). Outer package does not provide consumer with mandatory manufacturing/expiry date.",
      ],
    },
    evidence: [
      {
        id: "ev-501",
        storageKey: "reports/CR-2026-0005/box_bottom_blank.jpg",
        originalFileName: "carton_blank_mfg.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2540000,
        imageType: "OVERVIEW",
        url: "https://images.unsplash.com/photo-1608248597359-009772a0baec?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-08T15:20:00Z",
        resolution: "3024 x 4032",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-501",
        authorName: "Officer Sharma",
        authorRole: "Reviewer",
        content:
          "Report verified after inspecting all 6 carton sides. Blank date printing flap confirmed. Qualified for forward to Inspector Meenakshi Rathore for spot inspection.",
        createdAt: "2026-09-09T14:10:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-501",
        timestamp: "2026-09-08T15:40:00Z",
        action: "Report Submitted",
        actor: "Citizen #6780",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
      {
        id: "tl-502",
        timestamp: "2026-09-09T14:10:00Z",
        action: "Report Verified",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "UNDER_REVIEW",
        newStatus: "VERIFIED",
        details: "Verified as prima facie violation of Rule 6(1)(d).",
      },
    ],
    createdAt: "2026-09-08T15:40:00Z",
    updatedAt: "2026-09-09T14:10:00Z",
  },
  {
    id: "rep-006",
    reportNumber: "CR-2026-0006",
    userId: "usr-cit-7812",
    citizenNameMasked: "Rohit V. (Citizen #7812)",
    citizenPhoneMasked: "+91 94500-XXXXX",
    scanId: "scn-84979",
    issueType: "DEFACED_LABEL",
    issueLabel: "Defaced / Smudged Label",
    description:
      "Citizen reported that batch number and net quantity were intentionally smudged. However submitted photograph is heavily blurred and out of focus.",
    status: "REJECTED",
    priority: "LOW",
    shopName: "Avadh Supplement Hub",
    shopkeeperName: "Satish Yadav",
    shopAddress: "32 Hazratganj Metro Corridor, Hazratganj",
    shopCity: "Lucknow",
    shopState: "Uttar Pradesh",
    shopPinCode: "226001",
    latitude: 26.8467,
    longitude: 80.9462,
    locationAccuracy: 12.5,
    productSnapshot: {
      productName: "PowerCrunch Whey Protein Bar (60g)",
      brand: "MuscleFit Nutrition",
      category: "Health Supplements",
      declaredNetQuantity: "60 g",
      declaredMRP: "₹ 120.00",
    },
    analysisSnapshot: {
      ocrRawText: "POWERCRUNCH WHEY PROTEIN [UNREADABLE BLURRY CHARACTERS]",
      ocrConfidence: 34.0,
      detectedBarcodes: [],
      preliminaryResult: "INCONCLUSIVE",
      overallConfidence: 41.0,
      ruleChecks: [],
      highlightedIssues: ["Image quality insufficient for automated or manual verification."],
    },
    evidence: [
      {
        id: "ev-601",
        storageKey: "reports/CR-2026-0006/blurry_photo.jpg",
        originalFileName: "blurry_bar_photo.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 850000,
        imageType: "FRONT_LABEL",
        url: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-07T12:00:00Z",
        resolution: "1280 x 720",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-601",
        authorName: "Officer Sharma",
        authorRole: "Reviewer",
        content:
          "Rejected due to inadequate photo quality. Citizen was requested to re-photograph in daylight with tap-to-focus on label text.",
        createdAt: "2026-09-08T10:00:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-601",
        timestamp: "2026-09-07T12:30:00Z",
        action: "Report Submitted",
        actor: "Citizen #7812",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
      {
        id: "tl-602",
        timestamp: "2026-09-08T10:00:00Z",
        action: "Report Rejected",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "UNDER_REVIEW",
        newStatus: "REJECTED",
        details: "Reason: Inconclusive/blurry photographic evidence.",
      },
    ],
    createdAt: "2026-09-07T12:30:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
  },
  {
    id: "rep-007",
    reportNumber: "CR-2026-0007",
    userId: "usr-cit-8902",
    citizenNameMasked: "Hiren P. (Citizen #8902)",
    citizenPhoneMasked: "+91 98250-XXXXX",
    scanId: "scn-84988",
    issueType: "DUAL_MRP",
    issueLabel: "Overcharging Above Printed MRP at Railway Kiosk",
    description:
      "Bottled natural mineral water 1-Litre bottle clearly imprinted with MRP ₹20.00 (Incl. of all taxes) sold compulsorily at ₹35.00 with manual receipt charging 'Cooling & platform surcharge'.",
    status: "FORWARDED_TO_INSPECTOR",
    priority: "HIGH",
    shopName: "Platform 2 Refreshment Stall",
    shopkeeperName: "Kailash Chand",
    shopAddress: "Platform No. 2/3 Island, Kalupur Railway Station",
    shopCity: "Ahmedabad",
    shopState: "Gujarat",
    shopPinCode: "380002",
    latitude: 23.0276,
    longitude: 72.6009,
    locationAccuracy: 3.5,
    productSnapshot: {
      productName: "PureSpring Natural Mineral Water (1L)",
      brand: "PureSpring Aqua",
      genericName: "Packaged Drinking Water",
      category: "Beverages & Water",
      manufacturerName: "PureSpring Beverages Ltd",
      manufacturerAddress: "GIDC Estate, Naroda, Ahmedabad - 382330",
      countryOfOrigin: "India",
      declaredNetQuantity: "1.0 L",
      declaredMRP: "₹ 20.00",
      unitSalePrice: "₹ 0.02 / ml",
      monthYearOfManufacture: "03/2026",
      batchOrLotNumber: "PSA-26-091B",
      barcodeGTIN: "8901002233445",
      consumerCareEmail: "care@purespring.in",
      consumerCarePhone: "1800-425-0011",
    },
    analysisSnapshot: {
      ocrRawText: "PURESPRING NATURAL WATER 1L MRP RS 20.00 INCL ALL TAXES [INVOICE: ITEM 1 WATER RS 35.00]",
      ocrConfidence: 98.2,
      detectedBarcodes: ["8901002233445"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 97.5,
      ruleChecks: [
        {
          ruleNumber: "Rule 18(1)",
          ruleTitle: "Prohibition to Charge Beyond MRP",
          requirement: "No dealer shall sell any pre-packaged commodity at a price exceeding the retail sale price",
          declaredValue: "₹ 20.00 printed MRP",
          observedValue: "₹ 35.00 billed price on cash slip",
          status: "NON_COMPLIANT",
          confidenceScore: 99,
          notes: "Charging over MRP under guise of cooling charges is an offense under Section 36(1).",
        },
      ],
      highlightedIssues: [
        "Brazen 75% markup over printed statutory retail price in transit hub.",
        "Cash memo explicitly proves ₹35 billed for ₹20 printed item.",
      ],
    },
    evidence: [
      {
        id: "ev-701",
        storageKey: "reports/CR-2026-0007/water_bottle_mrp.jpg",
        originalFileName: "bottle_print_mrp20.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2190000,
        imageType: "MRP_STAMP",
        url: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-06T10:15:00Z",
        resolution: "3024 x 4032",
      },
      {
        id: "ev-702",
        storageKey: "reports/CR-2026-0007/kiosk_cash_slip.jpg",
        originalFileName: "railway_stall_receipt.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 1650000,
        imageType: "INVOICE",
        url: "https://images.unsplash.com/photo-1554415707-9e44667ff258?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-06T10:18:00Z",
        resolution: "2448 x 3264",
      },
    ],
    assignedReviewerId: "rev-current",
    assignedReviewerName: "Officer Sharma (You)",
    reviewNotes: [
      {
        id: "nt-701",
        authorName: "Officer Sharma",
        authorRole: "Reviewer",
        content:
          "Forwarded to Inspector Hitesh Patel with High Urgency. Railway stall operates under IRCTC/Commercial tender and is subject to immediate compounding notice under Section 36.",
        createdAt: "2026-09-07T11:20:00Z",
        isInternal: true,
      },
    ],
    timeline: [
      {
        id: "tl-701",
        timestamp: "2026-09-06T10:30:00Z",
        action: "Report Submitted",
        actor: "Citizen #8902",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
      {
        id: "tl-702",
        timestamp: "2026-09-07T11:00:00Z",
        action: "Report Verified",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "PENDING_REVIEW",
        newStatus: "VERIFIED",
      },
      {
        id: "tl-703",
        timestamp: "2026-09-07T11:20:00Z",
        action: "Forwarded to Inspector",
        actor: "Officer Sharma",
        actorRole: "Reviewer",
        previousStatus: "VERIFIED",
        newStatus: "FORWARDED_TO_INSPECTOR",
        details: "Assigned to Inspector Hitesh Patel (Ahmedabad Railway Zone).",
      },
    ],
    createdAt: "2026-09-06T10:30:00Z",
    updatedAt: "2026-09-07T11:20:00Z",
  },
  {
    id: "rep-008",
    reportNumber: "CR-2026-0008",
    userId: "usr-cit-9234",
    citizenNameMasked: "Deepak T. (Citizen #9234)",
    citizenPhoneMasked: "+91 97800-XXXXX",
    scanId: "scn-84994",
    issueType: "INCORRECT_WEIGHT",
    issueLabel: "Net Quantity Shortfall on Roasted Almonds",
    description:
      "Sealed 200g foil pouch of Roasted California Almonds weighed on certified electronic scale at 162.4g gross weight with packaging included. Actual net weight deficient by over 40 grams (20%).",
    status: "PENDING_REVIEW",
    priority: "HIGH",
    shopName: "Sector 17 Modern Grocers",
    shopkeeperName: "Jaswinder Singh",
    shopAddress: "SCF 22, Sector 17-C",
    shopCity: "Chandigarh",
    shopState: "Chandigarh (UT)",
    shopPinCode: "160017",
    latitude: 30.7398,
    longitude: 76.7827,
    locationAccuracy: 4.5,
    productSnapshot: {
      productName: "Premium California Roasted & Salted Almonds (200g)",
      brand: "NutriHarvest Dry Fruits",
      genericName: "Processed Edible Tree Nuts",
      category: "Packaged Foods & Dry Fruits",
      manufacturerName: "NutriHarvest Agro Foods Ltd",
      manufacturerAddress: "Kharar Industrial Area, Mohali, Punjab - 140301",
      countryOfOrigin: "USA (Raw Almonds) / Processed in India",
      declaredNetQuantity: "200 g",
      declaredMRP: "₹ 260.00",
      unitSalePrice: "₹ 1.30 / g",
      monthYearOfManufacture: "01/2026",
      expiryBestBefore: "6 Months from packaging",
      batchOrLotNumber: "NH-ALM-26A",
      barcodeGTIN: "8904567890123",
      consumerCareEmail: "help@nutriharvest.in",
      consumerCarePhone: "0172-4455660",
    },
    analysisSnapshot: {
      ocrRawText: "NUTRIHARVEST ROASTED ALMONDS NET WT 200g MRP RS 260.00 MOHALI PUNJAB BATCH NH-ALM-26A",
      ocrConfidence: 95.8,
      detectedBarcodes: ["8904567890123"],
      preliminaryResult: "POTENTIAL_VIOLATION",
      overallConfidence: 94.2,
      ruleChecks: [
        {
          ruleNumber: "Rule 6(1)(b)",
          ruleTitle: "Net Quantity Compliance",
          requirement: "Net weight within Maximum Permissible Error (MPE = 4.5g for 200g)",
          declaredValue: "200 g",
          observedValue: "162.4 g (Gross reading on scale)",
          status: "NON_COMPLIANT",
          confidenceScore: 97,
          notes: "37.6g shortfall exceeds MPE limit of 4.5g by over 800%.",
        },
      ],
      highlightedIssues: [
        "Severe shortfall in packaged net weight.",
        "Trade scale display clearly shows 162.4g with factory seal intact.",
      ],
    },
    evidence: [
      {
        id: "ev-801",
        storageKey: "reports/CR-2026-0008/scale_almonds.jpg",
        originalFileName: "almonds_on_trade_scale.jpg",
        mimeType: "image/jpeg",
        sizeBytes: 2840000,
        imageType: "WEIGHT_SCALE",
        url: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=1000&q=80",
        capturedAt: "2026-09-11T16:00:00Z",
        resolution: "3024 x 4032",
      },
    ],
    assignedReviewerId: undefined,
    reviewNotes: [],
    timeline: [
      {
        id: "tl-801",
        timestamp: "2026-09-11T16:20:00Z",
        action: "Report Submitted",
        actor: "Citizen #9234",
        actorRole: "Consumer",
        previousStatus: "SUBMITTED",
        newStatus: "PENDING_REVIEW",
      },
    ],
    createdAt: "2026-09-11T16:20:00Z",
    updatedAt: "2026-09-11T16:20:00Z",
  },
];

export const MOCK_ISSUE_TYPE_DISTRIBUTION = [
  { issueType: "INCORRECT_WEIGHT", label: "Incorrect Weight / Quantity", count: 42, percentage: 32, color: "#DC2626" },
  { issueType: "DUAL_MRP", label: "Dual / Overwritten MRP", count: 35, percentage: 27, color: "#F59E0B" },
  { issueType: "DATE_DECLARATION_MISSING", label: "Missing Mfg/Expiry Date", count: 21, percentage: 16, color: "#1769AA" },
  { issueType: "MISSING_MFR_DETAILS", label: "Missing Manufacturer Details", count: 14, percentage: 11, color: "#627D98" },
  { issueType: "CONSUMER_CARE_ABSENT", label: "Consumer Care Missing", count: 10, percentage: 8, color: "#16A34A" },
  { issueType: "COUNTRY_OF_ORIGIN_MISSING", label: "Missing Country of Origin", count: 8, percentage: 6, color: "#0B1F33" },
];

export const MOCK_STATUS_DISTRIBUTION = [
  { status: "SUBMITTED", label: "Submitted", count: 18, color: "#627D98" },
  { status: "PENDING_REVIEW", label: "Pending Review", count: 24, color: "#F59E0B" },
  { status: "UNDER_REVIEW", label: "Under Review", count: 12, color: "#1769AA" },
  { status: "NEED_MORE_INFORMATION", label: "Need More Info", count: 6, color: "#D97706" },
  { status: "VERIFIED", label: "Verified", count: 38, color: "#16A34A" },
  { status: "REJECTED", label: "Rejected", count: 7, color: "#DC2626" },
  { status: "FORWARDED_TO_INSPECTOR", label: "Forwarded to Inspector", count: 14, color: "#0B1F33" },
];

export const MOCK_RECENT_REVIEWS = [
  {
    id: "rep-005",
    reportNumber: "CR-2026-0005",
    productName: "Glow Radiance Serum 30ml",
    brand: "DermaElite Naturals",
    outcome: "VERIFIED",
    outcomeLabel: "Verified / Violation Confirmed",
    reviewedAt: "Today, 14:10",
    reviewerName: "Officer Sharma",
    reasonSnippet: "Blank date stamp area on outer mono-carton confirmed under Rule 6(1)(d).",
  },
  {
    id: "rep-006",
    reportNumber: "CR-2026-0006",
    productName: "PowerCrunch Protein Bar 60g",
    brand: "MuscleFit Nutrition",
    outcome: "REJECTED",
    outcomeLabel: "Rejected (Inconclusive)",
    reviewedAt: "Yesterday, 10:00",
    reviewerName: "Officer Sharma",
    reasonSnippet: "Evidence photo blurred; requested citizen to resubmit in daylight.",
  },
  {
    id: "rep-007",
    reportNumber: "CR-2026-0007",
    productName: "PureSpring Mineral Water 1L",
    brand: "PureSpring Aqua",
    outcome: "FORWARDED_TO_INSPECTOR",
    outcomeLabel: "Forwarded to Inspector Patel",
    reviewedAt: "2 days ago, 11:20",
    reviewerName: "Officer Sharma",
    reasonSnippet: "Direct overcharging at railway station kiosk; assigned for physical enforcement.",
  },
];

export const MOCK_RECENT_ACTIVITY = [
  {
    id: "act-1",
    timestamp: "12 mins ago",
    title: "Review Started",
    description: "Officer Sharma opened report CR-2026-0002 for evidence validation.",
    icon: "search",
    type: "REVIEW_START",
  },
  {
    id: "act-2",
    timestamp: "45 mins ago",
    title: "Internal Note Added",
    description: "Added note on CR-2026-0001 regarding fill line discrepancy and MPE limits.",
    icon: "note",
    type: "NOTE_ADDED",
  },
  {
    id: "act-3",
    timestamp: "2 hours ago",
    title: "Report Assigned",
    description: "CR-2026-0001 assigned to Officer Sharma based on Punjab jurisdiction.",
    icon: "assign",
    type: "ASSIGNMENT",
  },
  {
    id: "act-4",
    timestamp: "3 hours ago",
    title: "Decision Recorded: Forwarded",
    description: "Report CR-2026-0007 forwarded to Inspector Hitesh Patel (High Urgency).",
    icon: "forward",
    type: "FORWARDED",
  },
  {
    id: "act-5",
    timestamp: "Yesterday",
    title: "Decision Recorded: Verified",
    description: "Report CR-2026-0005 marked as Verified under Legal Metrology Rule 6(1)(d).",
    icon: "check",
    type: "VERIFIED",
  },
];
